### ISSUE TITLE
python setup.py egg_info should not install astropy

### ISSUE THREAD

**Issue by astrofrog** [astropy/astroscrappy#2]
I noticed on Travis that the ``python setup.py egg_info`` builds are installing astropy, which should not happen:

```
...
Searching for astropy
Reading https://pypi.python.org/simple/astropy/
Reading http://astropy.org
Best match: astropy 1.0.4
Downloading https://pypi.python.org/packages/source/a/astropy/astropy-1.0.4.tar.gz#md5=6d4696a695129fb3566ddc9643a2a944
```

No dependencies should be installed when running ``egg_info``.

**Comment by cmccully** [comment]
I think this is related to astropy/package-template#131 The issue here is that numpy and cython are required for build and build_ext, while astropy should be included in install_requires. While I'm happy to remove the astropy from setup_requires, what are your suggestions about how to deal with cython and numpy? This was the only way I was able to get things to build correctly on Travis.

**Comment by astrofrog** [comment]
@cmccully - just added a comment to https://github.com/astropy/package-template/pull/131

**Comment by astrofrog** [comment]
The bottom line is, if the user is running ``egg_info`` and other similar commands, ``setup_requires`` should definitely be empty.

**Comment by cmccully** [comment]
Ok. Thanks! I will fix that.

**Comment by cmccully** [comment]
I think this should be fixed, so I am closing this.
